### ISSUE TITLE
.Net 8 支援問題

### ISSUE THREAD

**Issue by Edemilorhea** [maxzh1999tw/Excely#15]
想請問目前.Net 8 是適合使用的嗎?

公司專案的目前想把ClosedXML改可以讀取CSV的套件，但專案是.Net 8，所以想先詢問看看

**Comment by maxzh1999tw** [comment]
抱歉這麼久才發現您的提問，這個套件完全就是為 .NET 7 以上設計的，所以 .NET 8應該可以正常使用喔，如果有問題的話歡迎再回報給我。
