### ISSUE TITLE
ClassListExporter我建議可以使用“組合“的方式更好的優化程式碼

### ISSUE THREAD

**Issue by s750022s** [maxzh1999tw/Excely#5]
Hi,Max.
您所寫的這個套件實用性很高，我很喜歡。
在ClassListExporter.cs裡，您使用繼承核心邏輯方式創建ClassListExporter，
未來如果想要加上匯出csv或其他格式時，可能會造成程式碼臃腫，不易延展。
也許可以使用“組合“取代“繼承“來達到更好的效果。

**Comment by maxzh1999tw** [comment]
你說的對，我當初是為了偷懶才使用繼承簡化程式碼，
確實會導致擴展上的困難，
用組合才是正確的。

你可以幫我修改嗎?

**Comment by s750022s** [comment]
當然可以，這是我的榮幸。

**Comment by s750022s** [comment]
Hi,Max.
[Pull requests網址](https://github.com/maxzh1999tw/Excely/pull/6)
我試著調整了程式碼，可以麻煩您幫我看看嗎?
感謝。
